/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarLinkRouteImport } from './routes/verificar-link'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminRemovalRouteImport } from './routes/admin/removal'

const VerificarLinkRoute = VerificarLinkRouteImport.update({
  id: '/verificar-link',
  path: '/verificar-link',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRemovalRoute = AdminRemovalRouteImport.update({
  id: '/admin/removal',
  path: '/admin/removal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inicio': typeof InicioRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorio': typeof RelatorioRoute
  '/termos': typeof TermosRoute
  '/verificar-link': typeof VerificarLinkRoute
  '/admin/removal': typeof AdminRemovalRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inicio': typeof InicioRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorio': typeof RelatorioRoute
  '/termos': typeof TermosRoute
  '/verificar-link': typeof VerificarLinkRoute
  '/admin/removal': typeof AdminRemovalRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inicio': typeof InicioRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorio': typeof RelatorioRoute
  '/termos': typeof TermosRoute
  '/verificar-link': typeof VerificarLinkRoute
  '/admin/removal': typeof AdminRemovalRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inicio'
    | '/onboarding'
    | '/privacidade'
    | '/relatorio'
    | '/termos'
    | '/verificar-link'
    | '/admin/removal'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inicio'
    | '/onboarding'
    | '/privacidade'
    | '/relatorio'
    | '/termos'
    | '/verificar-link'
    | '/admin/removal'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/inicio'
    | '/onboarding'
    | '/privacidade'
    | '/relatorio'
    | '/termos'
    | '/verificar-link'
    | '/admin/removal'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InicioRoute: typeof InicioRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RelatorioRoute: typeof RelatorioRoute
  TermosRoute: typeof TermosRoute
  VerificarLinkRoute: typeof VerificarLinkRoute
  AdminRemovalRoute: typeof AdminRemovalRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar-link': {
      id: '/verificar-link'
      path: '/verificar-link'
      fullPath: '/verificar-link'
      preLoaderRoute: typeof VerificarLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/removal': {
      id: '/admin/removal'
      path: '/admin/removal'
      fullPath: '/admin/removal'
      preLoaderRoute: typeof AdminRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InicioRoute: InicioRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RelatorioRoute: RelatorioRoute,
  TermosRoute: TermosRoute,
  VerificarLinkRoute: VerificarLinkRoute,
  AdminRemovalRoute: AdminRemovalRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
